import { Song } from "../interfaces/song";

export const Kpop: Song[] = [
  {
    title: "Dilemma",
    artist: "Apink",
    album: "HORN",
    display: true,
  },
  {
    title: "I want you to be happy",
    artist: "Apink",
    album: "Single",
    display: true,
  },
  {
    title: "Drama",
    artist: "aespa",
    album: "Drama - The 4th Mini Album",
    display: true,
  },
  {
    title: "Trick or Trick",
    artist: "aespa",
    album: "Drama - The 4th Mini Album",
    display: true,
  },
  {
    title: "YOLO",
    artist: "aespa",
    album: "Drama - The 4th Mini Album",
    display: true,
  },
  {
    title: "You",
    artist: "aespa",
    album: "Drama - The 4th Mini Album",
    display: true,
  },
  {
    title: "Thirsty",
    artist: "aespa",
    album: "MY WORLD - The 3rd Mini Album",
    display: true,
  },
  {
    title: "I'm Unhappy",
    artist: "aespa",
    album: "MY WORLD - The 3rd Mini Album",
    display: true,
  },
  {
    title: "'Til We Meet Again",
    artist: "aespa",
    album: "MY WORLD - The 3rd Mini Album",
    display: true,
  },
  {
    title: "Better Things",
    artist: "aespa",
    album: "Single",
    display: true,
  },
  {
    title: "Hold On Tight",
    artist: "aespa",
    album: "Single",
    display: true,
  },

  {
    title: "WHISTLE",
    artist: "BLACKPINK",
    album: "SQUARE ONE",
    display: true,
  },
  {
    title: "BOOMBAYAH",
    artist: "BLACKPINK",
    album: "SQUARE ONE",
  },
  {
    title: "PLAYING WITH FIRE",
    artist: "BLACKPINK",
    album: "SQUARE TWO",
  },
  {
    title: "STAY",
    artist: "BLACKPINK",
    album: "SQUARE TWO",
    display: true,
  },
  {
    title: "As If It's Your Last",
    artist: "BLACKPINK",
    album: "Single",
    display: true,
  },
  {
    title: "DDU-DU DDU-DU",
    artist: "BLACKPINK",
    album: "SQUARE UP",
    display: true,
  },
  {
    title: "Forever Young",
    artist: "BLACKPINK",
    album: "SQUARE UP",
    display: true,
  },
  {
    title: "Kill This Love",
    artist: "BLACKPINK",
    album: "Kill This Love",
    display: true,
  },
  {
    title: "Don't Know What To Do",
    artist: "BLACKPINK",
    album: "Kill This Love",
    display: true,
  },
  {
    title: "Kick It",
    artist: "BLACKPINK",
    album: "Kill This Love",
    display: true,
  },
  {
    title: "Hope Not",
    artist: "BLACKPINK",
    album: "Kill This Love",
    display: true,
  },
  {
    title: "Yeah Yeah Yeah",
    artist: "BLACKPINK",
    album: "BORN PINK",
    display: true,
  },
  {
    title: "Hard To Love",
    artist: "BLACKPINK",
    album: "BORN PINK",
    display: true,
  },
  {
    title: "Tally",
    artist: "BLACKPINK",
    album: "BORN PINK",
    display: true,
  },
  {
    title: "Ready For Love",
    artist: "BLACKPINK",
    album: "BORN PINK",
    display: true,
  },

  {
    title: "Roller Coaster",
    artist: "CHUNG HA",
    album: "Offset",
  },
  {
    title: "Gotta Go",
    artist: "CHUNG HA",
    album: "Single",
  },
  {
    title: "Snapping",
    artist: "CHUNG HA",
    album: "Flourishing",
  },
  {
    title: "Stay Tonight",
    artist: "CHUNG HA",
    album: "Querencia",
  },
  {
    title: "PLAY (feat. Changmo)",
    artist: "CHUNG HA",
    album: "Querencia",
  },
  {
    title: "Everybody Has",
    artist: "CHUNG HA",
    album: "Querencia",
    display: true,
  },
  {
    title: "Howl",
    artist: "CHUU",
    album: "Howl",
    display: true,
  },
  {
    title: "Underwater",
    artist: "CHUU",
    album: "Howl",
    display: true,
  },
  {
    title: "My Palace",
    artist: "CHUU",
    album: "Howl",
    display: true,
  },
  {
    title: "Aliens",
    artist: "CHUU",
    album: "Howl",
    display: true,
  },
  {
    title: "Hitchhiker",
    artist: "CHUU",
    album: "Howl",
    display: true,
  },

  {
    title: "LOVE BOMB",
    artist: "fromis_9",
    album: "From.9",
    display: true,
  },
  {
    title: "WE GO",
    artist: "fromis_9",
    album: "9 WAY TICKET",
  },
  {
    title: "Talk & Talk",
    artist: "fromis_9",
    album: "Single",
  },
  {
    title: "Escape Room",
    artist: "fromis_9",
    album: "Midnight Guest",
  },
  {
    title: "DM",
    artist: "fromis_9",
    album: "Midnight Guest",
    display: true,
  },
  {
    title: "Stay This Way",
    artist: "fromis_9",
    album: "from our Memento Box",
    display: true,
  },
  {
    title: "Rewind",
    artist: "fromis_9",
    album: "from our Memento Box",
  },
  {
    title: "Attitude",
    artist: "fromis_9",
    album: "Unlock My World",
    display: true,
  },
  {
    title: "#menow",
    artist: "fromis_9",
    album: "Unlock My World",
    display: true,
  },
  {
    title: "Wishlist",
    artist: "fromis_9",
    album: "Unlock My World",
    display: true,
  },
  {
    title: "In The Mirror",
    artist: "fromis_9",
    album: "Unlock My World",
    display: true,
  },
  {
    title: "Don't Care",
    artist: "fromis_9",
    album: "Unlock My World",
    display: true,
  },
  {
    title: "Prom Night",
    artist: "fromis_9",
    album: "Unlock My World",
    display: true,
  },
  {
    title: "Bring It On",
    artist: "fromis_9",
    album: "Unlock My World",
    display: true,
  },
  {
    title: "What I Want",
    artist: "fromis_9",
    album: "Unlock My World",
    display: true,
  },
  {
    title: "My Night Routine",
    artist: "fromis_9",
    album: "Unlock My World",
    display: true,
  },
  {
    title: "Eye Contact",
    artist: "fromis_9",
    album: "Unlock My World",
    display: true,
  },
  {
    title: "Love Me Back",
    artist: "fromis_9",
    album: "Single",
    display: true,
  },

  {
    title: "Rough",
    artist: "GFRIEND",
    album: "GFRIEND 3rd Mini Album 'SNOWFLAKE'",
    display: true,
  },
  {
    title: "MAGO",
    artist: "GFRIEND",
    album: "回:Walpurgis Night",
    display: true,
  },

  {
    title: "Sad Girls Club",
    artist: "Heejin",
    album: "K",
  },
  {
    title: "Video Game",
    artist: "Heejin",
    album: "K",
    display: true,
  },
  {
    title: "Nokia",
    artist: "Heejin",
    album: "K",
    display: true,
  },
  {
    title: "One More Last Time",
    artist: "Henry Young feat. Ashley Alisha",
    album: "Single",
    display: true,
  },

  {
    title: "DALLA DALLA",
    artist: "ITZY",
    album: "IT'z Different",
  },
  {
    title: "ICY",
    artist: "ITZY",
    album: "IT'z ICY",
  },
  {
    title: "WANNABE",
    artist: "ITZY",
    album: "IT'z ME",
    display: true,
  },
  {
    title: "Trust Me (MIDZY)",
    artist: "ITZY",
    album: "Single",
    display: true,
  },
  {
    title: "In the morning",
    artist: "ITZY",
    album: "GUESS WHO",
  },
  {
    title: "LOCO",
    artist: "ITZY",
    album: "CRAZY IN LOVE",
    display: true,
  },
  {
    title: "Cheshire",
    artist: "ITZY",
    album: "Cheshire",
  },
  {
    title: "Boys Like You",
    artist: "ITZY",
    album: "Cheshire",
    display: true,
  },
  {
    title: "BET ON ME",
    artist: "ITZY",
    album: "KILL MY DOUBT",
    display: true,
  },
  {
    title: "None of My Business",
    artist: "ITZY",
    album: "KILL MY DOUBT",
  },
  {
    title: "Kill Shot",
    artist: "ITZY",
    album: "KILL MY DOUBT",
  },
  {
    title: "RINGO",
    artist: "ITZY",
    album: "RINGO",
  },
  {
    title: "Sugar-holic",
    artist: "ITZY",
    album: "RINGO",
  },
  {
    title: "Playlist",
    artist: "ITZY",
    album: "RINGO",
  },
  {
    title: "STYLE",
    artist: "ITZY",
    album: "RINGO",
  },
  {
    title: "Voltage",
    artist: "ITZY",
    album: "RINGO",
  },
  {
    title: "Spice",
    artist: "ITZY",
    album: "RINGO",
  },
  {
    title: "Blah Blah Blah",
    artist: "ITZY",
    album: "RINGO",
  },
  {
    title: "eight(Prod.&Feat. SUGA of BTS)",
    artist: "IU",
    album: "Single",
    display: true,
  },
  {
    title: "Celebrity",
    artist: "IU",
    album: "IU 5th Album 'LILAC'",
    display: true,
  },
  {
    title: "ELEVEN",
    artist: "IVE",
    album: "ELEVEN",
    display: true,
  },
  {
    title: "LOVE DIVE",
    artist: "IVE",
    album: "LOVE DIVE",
    display: true,
  },
  {
    title: "After LIKE",
    artist: "IVE",
    album: "After LIKE",
    display: true,
  },
  {
    title: "Blue Blood",
    artist: "IVE",
    album: "I'VE IVE",
  },
  {
    title: "I AM",
    artist: "IVE",
    album: "I'VE IVE",
    display: true,
  },
  {
    title: "Kitsch",
    artist: "IVE",
    album: "I'VE IVE",
  },
  {
    title: "Off The Record",
    artist: "IVE",
    album: "I'VE MINE",
    display: true,
  },
  {
    title: "Baddie",
    artist: "IVE",
    album: "I'VE MINE",
    display: true,
  },
  {
    title: "Either Way",
    artist: "IVE",
    album: "I'VE MINE",
    display: true,
  },
  {
    title: "Holy Moly",
    artist: "IVE",
    album: "I'VE MINE",
    display: true,
  },
  {
    title: "OTT",
    artist: "IVE",
    album: "I'VE MINE",
    display: true,
  },
  {
    title: "Payback",
    artist: "IVE",
    album: "I'VE MINE",
    display: true,
  },

  {
    title: "SOLO",
    artist: "JENNIE",
    album: "Single",
  },
  {
    title: "You & Me",
    artist: "JENNIE",
    album: "Single",
  },
  {
    title: "Killin' Me Good",
    artist: "JIHYO",
    album: "ZONE",
    display: true,
  },
  {
    title: "Talkin' About It (feat. 24kGoldn)",
    artist: "JIHYO",
    album: "ZONE",
    display: true,
  },
  {
    title: "Here We Go Again",
    artist: "JINI",
    album: "An Iron Hand In A Velvet Glove",
    display: true,
  },
  {
    title: "C'mon (feat. Aminé)",
    artist: "JINI",
    album: "An Iron Hand In A Velvet Glove",
    display: true,
  },
  {
    title: "Dancing With The Devil",
    artist: "JINI",
    album: "An Iron Hand In A Velvet Glove",
    display: true,
  },
  {
    title: "Bad Reputation",
    artist: "JINI",
    album: "An Iron Hand In A Velvet Glove",
    display: true,
  },
  {
    title: "FLOWER",
    artist: "JISOO",
    album: "ME",
    display: true,
  },
  {
    title: "All Eyes On Me",
    artist: "JISOO",
    album: "ME",
    display: true,
  },

  {
    title: "FEARLESS",
    artist: "LE SSERAFIM",
    album: "FEARLESS",
  },
  {
    title: "ANTIFRAGILE",
    artist: "LE SSERAFIM",
    album: "ANTIFRAGILE",
  },
  {
    title: "UNFORGIVEN (feat. Nile Rodgers)",
    artist: "LE SSERAFIM",
    album: "UNFORGIVEN",
  },
  {
    title: "Eve, Psyche & The Bluebeard's wife",
    artist: "LE SSERAFIM",
    album: "UNFORGIVEN",
    display: true,
  },
  {
    title: "Perfect Night",
    artist: "LE SSERAFIM",
    album: "Single",
    display: true,
  },
  {
    title: "Butterfly",
    artist: "LOONA",
    album: "[XX]",
  },
  {
    title: "So What",
    artist: "LOONA",
    album: "[#]",
    display: true,
  },
  {
    title: "365",
    artist: "LOONA",
    album: "[#]",
    display: true,
  },
  {
    title: "Why Not?",
    artist: "LOONA",
    album: "[12:00]",
    display: true,
  },
  {
    title: "Voice",
    artist: "LOONA",
    album: "[12:00]",
    display: true,
  },
  {
    title: "Universe",
    artist: "LOONA",
    album: "[12:00]",
    display: true,
  },
  {
    title: "PTT (Paint The Town)",
    artist: "LOONA",
    album: "[&]",
    display: true,
  },
  {
    title: "POSE",
    artist: "LOONA",
    album: "Summer Special [Flip That]",
  },
  {
    title: "LUMINOUS",
    artist: "LOONA",
    album: "Single",
    display: true,
  },
  {
    title: "Sensitive",
    artist: "Loossemble",
    album: "Loossemble",
    display: true,
  },
  {
    title: "Real world",
    artist: "Loossemble",
    album: "Loossemble",
    display: true,
  },
  {
    title: "Colouring",
    artist: "Loossemble",
    album: "Loossemble",
    display: true,
  },
  {
    title: "Newtopia",
    artist: "Loossemble",
    album: "Loossemble",
    display: true,
  },
  {
    title: "Strawberry soda",
    artist: "Loossemble",
    album: "Loossemble",
    display: true,
  },
  {
    title: "Day by day",
    artist: "Loossemble",
    album: "Loossemble",
    display: true,
  },

  {
    title: "POP!",
    artist: "NAYEON",
    album: "IM NAYEON",
    display: true,
  },
  {
    title: "NO PROBLEM (feat. Felix of Stray Kids)",
    artist: "NAYEON",
    album: "IM NAYEON",
    display: true,
  },
  {
    title: "LOVE COUNTDOWN (feat. Wonstein)",
    artist: "NAYEON",
    album: "IM NAYEON",
    display: true,
  },
  {
    title: "SUNSET",
    artist: "NAYEON",
    album: "IM NAYEON",
    display: true,
  },
  {
    title: "Attention",
    artist: "NewJeans",
    album: "NewJeans 1st EP 'New Jeans'",
    display: true,
  },
  {
    title: "Hype Boy",
    artist: "NewJeans",
    album: "NewJeans 1st EP 'New Jeans'",
    display: true,
  },
  {
    title: "Hurt",
    artist: "NewJeans",
    album: "NewJeans 1st EP 'New Jeans'",
    display: true,
  },
  {
    title: "OMG",
    artist: "NewJeans",
    album: "NewJeans 'OMG'",
    display: true,
  },
  {
    title: "Ditto",
    artist: "NewJeans",
    album: "NewJeans 'OMG'",
    display: true,
  },
  {
    title: "New Jeans",
    artist: "NewJeans",
    album: "NewJeans 2nd EP 'Get Up'",
    display: true,
  },
  {
    title: "Super Shy",
    artist: "NewJeans",
    album: "NewJeans 2nd EP 'Get Up'",
    display: true,
  },
  {
    title: "ETA",
    artist: "NewJeans",
    album: "NewJeans 2nd EP 'Get Up'",
    display: true,
  },
  {
    title: "Cool With You",
    artist: "NewJeans",
    album: "NewJeans 2nd EP 'Get Up'",
    display: true,
  },
  {
    title: "Get Up",
    artist: "NewJeans",
    album: "NewJeans 2nd EP 'Get Up'",
    display: true,
  },
  {
    title: "ASAP",
    artist: "NewJeans",
    album: "NewJeans 2nd EP 'Get Up'",
    display: true,
  },
  {
    title: "GODS",
    artist: "NewJeans",
    album: "Single",
    display: true,
  },
  {
    title: "Beautiful Restriction",
    artist: "NewJeans",
    album: "Single",
    display: true,
  },
  {
    title: "Our Night is more beautiful than your Day",
    artist: "NewJeans",
    album: "Single",
    display: true,
  },
  {
    title: "TANK",
    artist: "NMIXX",
    album: "AD MARE",
    display: true,
  },
  {
    title: "O.O",
    artist: "NMIXX",
    album: "AD MARE",
    display: true,
  },
  {
    title: "Kiss",
    artist: "NMIXX",
    album: "Single",
    display: true,
  },
  {
    title: "DICE",
    artist: "NMIXX",
    album: "ENTWURF",
    display: true,
  },
  {
    title: "COOL (Your rainbow)",
    artist: "NMIXX",
    album: "ENTWURF",
    display: true,
  },
  {
    title: "Love Me Like This",
    artist: "NMIXX",
    album: "expérgo",
  },
  {
    title: "Party O'Clock",
    artist: "NMIXX",
    album: "A Midsummer NMIXX's Dream",
  },
  {
    title: "Roller Coaster",
    artist: "NMIXX",
    album: "A Midsummer NMIXX's Dream",
  },
  {
    title: "Soñar (Breaker)",
    artist: "NMIXX",
    album: "Single",
    display: true,
  },

  {
    title: "Air Force One",
    artist: "Odd Eye Circle",
    album: "Version Up",
    display: true,
  },
  {
    title: "Je Ne Sais Quoi",
    artist: "Odd Eye Circle",
    album: "Version Up",
    display: true,
  },
  {
    title: "Lucid",
    artist: "Odd Eye Circle",
    album: "Version Up",
    display: true,
  },
  {
    title: "My Secret Playlist",
    artist: "Odd Eye Circle",
    album: "Version Up",
    display: true,
  },

  {
    title: "Dream lantern",
    artist: "RADWIMPS",
    album: "Your Name.",
    display: true,
  },
  {
    title: "Zenzenzense - movie ver.",
    artist: "RADWIMPS",
    album: "Your Name.",
    display: true,
  },
  {
    title: "Sparkle - movie ver.",
    artist: "RADWIMPS",
    album: "Your Name.",
    display: true,
  },
  {
    title: "Nandemonaiya - movie ver.",
    artist: "RADWIMPS",
    album: "Your Name.",
    display: true,
  },
  {
    title: "Happiness",
    artist: "Red Velvet",
    album: "Single",
  },
  {
    title: "Automatic",
    artist: "Red Velvet",
    album: "Ice Cream Cake - The 1st Mini Album",
  },
  {
    title: "Dumb Dumb",
    artist: "Red Velvet",
    album: "The Red - The 1st Album",
  },
  {
    title: "One Of These Nights",
    artist: "Red Velvet",
    album: "The Velvet - The 2nd Mini Album",
    display: true,
  },
  {
    title: "Russian Roulette",
    artist: "Red Velvet",
    album: "Russian Roulette - The 3rd Mini Album",
    display: true,
  },
  {
    title: "Red Flavor",
    artist: "Red Velvet",
    album: "The Red Summer - Summer Mini Album",
    display: true,
  },
  {
    title: "Peek-A-Boo",
    artist: "Red Velvet",
    album: "Perfect Velvet - The 2nd Album",
  },
  {
    title: "Bad Boy",
    artist: "Red Velvet",
    album: "The Perfect Red Velvet - The 2nd Album Repackage",
    display: true,
  },
  {
    title: "Power Up",
    artist: "Red Velvet",
    album: "Summer Magic - Summer Mini Album",
  },
  {
    title: "Sayonara",
    artist: "Red Velvet",
    album: "Single",
    display: true,
  },
  {
    title: "Rebirth",
    artist: "Red Velvet",
    album: "Single",
    display: true,
  },
  {
    title: "Zimzalabim",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Day 1",
    display: true,
  },
  {
    title: "Sunny Side Up!",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Day 1",
    display: true,
  },
  {
    title: "Bing Bing",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Day 1",
    display: true,
  },
  {
    title: "Parade",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Day 1",
    display: true,
  },
  {
    title: "LP",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Day 1",
    display: true,
  },
  {
    title: "Umpah Umpah",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Day 2",
    display: true,
  },
  {
    title: "Carpool",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Day 2",
    display: true,
  },
  {
    title: "Love Is The Way",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Day 2",
    display: true,
  },
  {
    title: "Jumpin'",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Day 2",
    display: true,
  },
  {
    title: "Eyes Locked, Hands Locked",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Day 2",
    display: true,
  },
  {
    title: "Psycho",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Finale",
    display: true,
  },
  {
    title: "In & Out",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Finale",
    display: true,
  },
  {
    title: "Remember Forever",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Finale",
    display: true,
  },
  {
    title: "La Rouge - Special Track",
    artist: "Red Velvet",
    album: "'The ReVe Festival' Finale",
    display: true,
  },
  {
    title: "Milky Way",
    artist: "Red Velvet",
    album: "Single",
    display: true,
  },
  {
    title: "Future",
    artist: "Red Velvet",
    album: "Single",
    display: true,
  },
  {
    title: "Queendom",
    artist: "Red Velvet",
    album: "Queendom - The 6th Mini Album",
    display: true,
  },
  {
    title: "Pose",
    artist: "Red Velvet",
    album: "Queendom - The 6th Mini Album",
    display: true,
  },
  {
    title: "Knock On Wood",
    artist: "Red Velvet",
    album: "Queendom - The 6th Mini Album",
  },
  {
    title: "Pushin' N Pullin'",
    artist: "Red Velvet",
    album: "Queendom - The 6th Mini Album",
  },
  {
    title: "Hello, Sunset",
    artist: "Red Velvet",
    album: "Queendom - The 6th Mini Album",
  },
  {
    title: "Feel My Rhythm",
    artist: "Red Velvet",
    album: "'The ReVe Festival 2022 - Feel My Rhythm'",
    display: true,
  },
  {
    title: "Rainbow Halo",
    artist: "Red Velvet",
    album: "'The ReVe Festival 2022 - Feel My Rhythm'",
  },
  {
    title: "Beg For Me",
    artist: "Red Velvet",
    album: "'The ReVe Festival 2022 - Feel My Rhythm'",
    display: true,
  },
  {
    title: "BAMBOLEO",
    artist: "Red Velvet",
    album: "'The ReVe Festival 2022 - Feel My Rhythm'",
  },
  {
    title: "Good, Bad, Ugly",
    artist: "Red Velvet",
    album: "'The ReVe Festival 2022 - Feel My Rhythm'",
    display: true,
  },
  {
    title: "In My Dreams",
    artist: "Red Velvet",
    album: "'The ReVe Festival 2022 - Feel My Rhythm'",
    display: true,
  },
  {
    title: "WILDSIDE",
    artist: "Red Velvet",
    album: "Bloom",
    display: true,
  },
  {
    title: "Birthday",
    artist: "Red Velvet",
    album: "'The ReVe Festival 2022 - Birthday'",
  },
  {
    title: "BYE BYE",
    artist: "Red Velvet",
    album: "'The ReVe Festival 2022 - Birthday'",
  },
  {
    title: "On A Ride",
    artist: "Red Velvet",
    album: "'The ReVe Festival 2022 - Birthday'",
  },
  {
    title: "ZOOM",
    artist: "Red Velvet",
    album: "'The ReVe Festival 2022 - Birthday'",
  },
  {
    title: "Celebrate",
    artist: "Red Velvet",
    album: "'The ReVe Festival 2022 - Birthday'",
  },
  {
    title: "Chill Kill",
    artist: "Red Velvet",
    album: "Chill Kill - The 3rd Album",
    display: true,
  },
  {
    title: "Underwater",
    artist: "Red Velvet",
    album: "Chill Kill - The 3rd Album",
    display: true,
  },
  {
    title: "Will I Ever See You Again?",
    artist: "Red Velvet",
    album: "Chill Kill - The 3rd Album",
    display: true,
  },
  {
    title: "Nightmare",
    artist: "Red Velvet",
    album: "Chill Kill - The 3rd Album",
    display: true,
  },
  {
    title: "Bulldozer",
    artist: "Red Velvet",
    album: "Chill Kill - The 3rd Album",
    display: true,
  },
  {
    title: "Scenery",
    artist: "Red Velvet",
    album: "Chill Kill - The 3rd Album",
    display: true,
  },
  {
    title: "On The Ground",
    artist: "ROSÉ",
    album: "R",
    display: true,
  },
  {
    title: "Gone",
    artist: "ROSÉ",
    album: "R",
    display: true,
  },

  {
    title: "28 Reasons",
    artist: "SEULGI",
    album: "28 Reasons - The 1st Mini Album",
    display: true,
  },
  {
    title: "Dead Man Runnin'",
    artist: "SEULGI",
    album: "28 Reasons - The 1st Mini Album",
    display: true,
  },
  {
    title: "Anywhere But Home",
    artist: "SEULGI",
    album: "28 Reasons - The 1st Mini Album",
    display: true,
  },
  {
    title: "Crown",
    artist: "SEULGI",
    album: "28 Reasons - The 1st Mini Album",
    display: true,
  },
  {
    title: "SO BAD",
    artist: "STAYC",
    album: "Star To A Young Culture",
    display: true,
  },
  {
    title: "ASAP",
    artist: "STAYC",
    album: "STAYDOM",
  },
  {
    title: "STEREOTYPE",
    artist: "STAYC",
    album: "STEREOTYPE",
  },
  {
    title: "RUN2U",
    artist: "STAYC",
    album: "YOUNG-LUV.COM",
    display: true,
  },
  {
    title: "SAME SAME",
    artist: "STAYC",
    album: "YOUNG-LUV.COM",
  },
  {
    title: "247",
    artist: "STAYC",
    album: "YOUNG-LUV.COM",
  },
  {
    title: "YOUNG LUV",
    artist: "STAYC",
    album: "YOUNG-LUV.COM",
    display: true,
  },
  {
    title: "BUTTERFLY",
    artist: "STAYC",
    album: "YOUNG-LUV.COM",
  },
  {
    title: "I WANT U BABY",
    artist: "STAYC",
    album: "YOUNG-LUV.COM",
  },
  {
    title: "STAR",
    artist: "STAYC",
    album: "Single",
    display: true,
  },
  {
    title: "BEAUTIFUL MONSTER",
    artist: "STAYC",
    album: "WE NEED LOVE",
    display: true,
  },
  {
    title: "I LIKE IT",
    artist: "STAYC",
    album: "WE NEED LOVE",
    display: true,
  },
  {
    title: "LOVE",
    artist: "STAYC",
    album: "WE NEED LOVE",
    display: true,
  },
  {
    title: "Bubble",
    artist: "STAYC",
    album: "TEENFRESH",
    display: true,
  },
  {
    title: "Not Like You",
    artist: "STAYC",
    album: "TEENFRESH",
    display: true,
  },
  {
    title: "I Wanna Do",
    artist: "STAYC",
    album: "TEENFRESH",
    display: true,
  },
  {
    title: "Be Mine",
    artist: "STAYC",
    album: "TEENFRESH",
    display: true,
  },

  {
    title: "Blue",
    artist: "TAEYEON",
    album: "Four Seasons",
    display: true,
  },
  {
    title: "Gravity",
    artist: "TAEYEON",
    album: "Purpose - The 2nd Album",
    display: true,
  },
  {
    title: "Dear Me",
    artist: "TAEYEON",
    album: "Purpose - The 2nd Album Repackage",
    display: true,
  },
  {
    title: "Drawing Our Moments",
    artist: "TAEYEON",
    album: "Purpose - The 2nd Album Repackage",
    display: true,
  },
  {
    title: "INVU",
    artist: "TAEYEON",
    album: "INVU - The 3rd Album",
    display: true,
  },
  {
    title: "To. X",
    artist: "TAEYEON",
    album: "To. X - The 5th Mini Album",
    display: true,
  },
  {
    title: "Nightmare",
    artist: "TAEYEON",
    album: "To. X - The 5th Mini Album",
  },
  {
    title: "All For Nothing",
    artist: "TAEYEON",
    album: "To. X - The 5th Mini Album",
    display: true,
  },
  {
    title: "Feel Special",
    artist: "TWICE",
    album: "Feel Special",
    display: true,
  },
  {
    title: "Rainbow",
    artist: "TWICE",
    album: "Feel Special",
    display: true,
  },
  {
    title: "Get Loud",
    artist: "TWICE",
    album: "Feel Special",
    display: true,
  },
  {
    title: "Trick It",
    artist: "TWICE",
    album: "Feel Special",
    display: true,
  },
  {
    title: "Love Foolish",
    artist: "TWICE",
    album: "Feel Special",
    display: true,
  },
  {
    title: "21:29",
    artist: "TWICE",
    album: "Feel Special",
    display: true,
  },
  {
    title: "Fake & True",
    artist: "TWICE",
    album: "&TWICE",
    display: true,
  },
  {
    title: "Stronger",
    artist: "TWICE",
    album: "&TWICE",
    display: true,
  },
  {
    title: "Breakthrough",
    artist: "TWICE",
    album: "&TWICE",
    display: true,
  },
  {
    title: "Changing!",
    artist: "TWICE",
    album: "&TWICE",
    display: true,
  },
  {
    title: "HAPPY HAPPY",
    artist: "TWICE",
    album: "&TWICE",
    display: true,
  },
  {
    title: "What You Waiting For",
    artist: "TWICE",
    album: "&TWICE",
    display: true,
  },
  {
    title: "Talk That Talk",
    artist: "TWICE",
    album: "BETWEEN 1&2",
    display: true,
  },
  {
    title: "Basics",
    artist: "TWICE",
    album: "BETWEEN 1&2",
    display: true,
  },
  {
    title: "Gone",
    artist: "TWICE",
    album: "BETWEEN 1&2",
    display: true,
  },

  {
    title: "MANIAC",
    artist: "VIVIZ",
    album: "The 4th Mini Album 'VERSUS'",
    display: true,
  },
  {
    title: "Untie",
    artist: "VIVIZ",
    album: "The 4th Mini Album 'VERSUS'",
    display: true,
  },
  {
    title: "Overflow",
    artist: "VIVIZ",
    album: "The 4th Mini Album 'VERSUS'",
    display: true,
  },
  {
    title: "Day by day",
    artist: "VIVIZ",
    album: "The 4th Mini Album 'VERSUS'",
    display: true,
  },
  {
    title: "Up 2 Me",
    artist: "VIVIZ",
    album: "The 4th Mini Album 'VERSUS'",
    display: true,
  },

  {
    title: "When This Rain Stops",
    artist: "WENDY",
    album: "Like Water - The 1st Mini Album",
    display: true,
  },
  {
    title: "Like Water",
    artist: "WENDY",
    album: "Like Water - The 1st Mini Album",
    display: true,
  },
  {
    title: "The Road",
    artist: "WENDY",
    album: "Like Water - The 1st Mini Album",
    display: true,
  },
  {
    title: "Best Friend (with SEULGI)",
    artist: "WENDY",
    album: "Like Water - The 1st Mini Album",
    display: true,
  },
];
