import { Song } from "../interfaces/song";

export const Pop: Song[] = [
  {
    title: "Blank Space (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Style (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Out Of The Woods (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "All You Had To Do Was Stay (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Shake It Off (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "I Wish You Would (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Bad Blood (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Wildest Dreams (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "How You Get The Girl (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "This Love (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "I Know Places (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Clean (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Wonderland (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "You Are In Love (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "New Romantics (Taylor's Version)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: `"Slut!" (Taylor's Version) (From The Vault)`,
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Say Don't Go (Taylor's Version) (From The Vault)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Now That We Don't Talk (Taylor's Version) (From The Vault)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Suburban Legends (Taylor's Version) (From The Vault)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Is It Over Now? (Taylor's Version) (From The Vault)",
    artist: "Taylor Swift",
    album: "1989 (Taylor's Version)",
    display: true,
  },
  {
    title: "Lavender Haze",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Maroon",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Anti-Hero",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Snow On The Beach (feat. Lana Del Rey)",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "You're On Your Own Kid",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Midnight Rain",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Question...?",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Vigilante Shit",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Bejeweled",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Labyrinth",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Karma",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Sweet Nothing",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Mastermind",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Paris",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "High Infidelity",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Glitch",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Would've Could've Should've",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Dear Reader",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "Hits Different",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "You're Losing Me",
    artist: "Taylor Swift",
    album: "Midnights",
    display: true,
  },
  {
    title: "So Special",
    artist: "MUNA",
    album: "About U",
    display: true,
  },
  {
    title: "Loudspeaker",
    artist: "MUNA",
    album: "About U",
    display: true,
  },
  {
    title: "I Know A Place",
    artist: "MUNA",
    album: "About U",
    display: true,
  },
  {
    title: "Winterbreak",
    artist: "MUNA",
    album: "About U",
    display: true,
  },
  {
    title: "Around U",
    artist: "MUNA",
    album: "About U",
    display: true,
  },
  {
    title: "End of Desire",
    artist: "MUNA",
    album: "About U",
    display: true,
  },
  {
    title: "Everything",
    artist: "MUNA",
    album: "About U",
    display: true,
  },
  {
    title: "Outro",
    artist: "MUNA",
    album: "About U",
    display: true,
  },
  {
    title: "Stayaway",
    artist: "MUNA",
    album: "Saves The World",
    display: true,
  },
  {
    title: "Who",
    artist: "MUNA",
    album: "Saves The World",
    display: true,
  },
  {
    title: "Navy Blue",
    artist: "MUNA",
    album: "Saves The World",
    display: true,
  },
  {
    title: "Pink Light",
    artist: "MUNA",
    album: "Saves The World",
    display: true,
  },
  {
    title: "Taken",
    artist: "MUNA",
    album: "Saves The World",
    display: true,
  },
  {
    title: "Good News (Ya-Ya Song)",
    artist: "MUNA",
    album: "Saves The World",
    display: true,
  },
  {
    title: "Memento",
    artist: "MUNA",
    album: "Saves The World",
    display: true,
  },
  {
    title: "It's Gonna Be Okay, Baby",
    artist: "MUNA",
    album: "Saves The World",
    display: true,
  },
  {
    title: "What I Want",
    artist: "MUNA",
    album: "MUNA",
    display: true,
  },
  {
    title: "Home By Now",
    artist: "MUNA",
    album: "MUNA",
    display: true,
  },
  {
    title: "Kind Of Girl",
    artist: "MUNA",
    album: "MUNA",
    display: true,
  },
  {
    title: "Loose Garment",
    artist: "MUNA",
    album: "MUNA",
    display: true,
  },
  {
    title: "Shooting Star",
    artist: "MUNA",
    album: "MUNA",
    display: true,
  },
  {
    title: "Tennis Court",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "400 Lux",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "Royals",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "Ribs",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "Buzzcut Season",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "Team",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "White Teeth Teens",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "A World Alone",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "No Better",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "Bravado",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "Million Dollar Bills",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "The Love Club",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "Biting Down",
    artist: "Lorde",
    album: "Pure Heroine",
    display: true,
  },
  {
    title: "Green Light",
    artist: "Lorde",
    album: "Melodrama",
    display: true,
  },
  {
    title: "Sober",
    artist: "Lorde",
    album: "Melodrama",
    display: true,
  },
  {
    title: "Homemade Dynamite",
    artist: "Lorde",
    album: "Melodrama",
    display: true,
  },
  {
    title: "The Louvre",
    artist: "Lorde",
    album: "Melodrama",
    display: true,
  },
  {
    title: "Liability",
    artist: "Lorde",
    album: "Melodrama",
    display: true,
  },
  {
    title: "Hard Feelings / Loveless",
    artist: "Lorde",
    album: "Melodrama",
    display: true,
  },
  {
    title: "Sober II (Melodrama)",
    artist: "Lorde",
    album: "Melodrama",
    display: true,
  },
  {
    title: "Supercut",
    artist: "Lorde",
    album: "Melodrama",
    display: true,
  },
  {
    title: "Liability (Reprise)",
    artist: "Lorde",
    album: "Melodrama",
    display: true,
  },
  {
    title: "Perfect Places",
    artist: "Lorde",
    album: "Melodrama",
    display: true,
  },
  {
    title: "Stoned at the Nail Salon",
    artist: "Lorde",
    album: "Solar Power",
    display: true,
  },
  {
    title: "Fallen Fruit",
    artist: "Lorde",
    album: "Solar Power",
    display: true,
  },
  {
    title: "Secrets from a Girl (Who's Seen it All)",
    artist: "Lorde",
    album: "Solar Power",
    display: true,
  },
  {
    title: "Dominoes",
    artist: "Lorde",
    album: "Solar Power",
    display: true,
  },
  {
    title: "Big Star",
    artist: "Lorde",
    album: "Solar Power",
    display: true,
  },
  {
    title: "Mood Ring",
    artist: "Lorde",
    album: "Solar Power",
    display: true,
  },
  {
    title: "Oceanic Feeling",
    artist: "Lorde",
    album: "Solar Power",
    display: true,
  },
  {
    title: "Helen of Troy",
    artist: "Lorde",
    album: "Solar Power",
    display: true,
  },
  {
    title: "Hold No Grudge",
    artist: "Lorde",
    album: "Solar Power",
    display: true,
  },
  {
    title: "Is There Somewhere",
    artist: "Halsey",
    album: "Room 93 - EP",
    display: true,
  },
  {
    title: "Castle",
    artist: "Halsey",
    album: "BADLANDS",
    display: true,
  },
  {
    title: "Hold Me Down",
    artist: "Halsey",
    album: "BADLANDS",
    display: true,
  },
  {
    title: "New Americana",
    artist: "Halsey",
    album: "BADLANDS",
    display: true,
  },
  {
    title: "Drive",
    artist: "Halsey",
    album: "BADLANDS",
    display: true,
  },
  {
    title: "Hurricane",
    artist: "Halsey",
    album: "BADLANDS",
    display: true,
  },
  {
    title: "Roman Holiday",
    artist: "Halsey",
    album: "BADLANDS",
    display: true,
  },
  {
    title: "Ghost",
    artist: "Halsey",
    album: "BADLANDS",
    display: true,
  },
  {
    title: "Colors",
    artist: "Halsey",
    album: "BADLANDS",
    display: true,
  },
  {
    title: "100 Letters",
    artist: "Halsey",
    album: "hopeless fountain kingdom",
    display: true,
  },
  {
    title: "Alone",
    artist: "Halsey",
    album: "hopeless fountain kingdom",
    display: true,
  },
  {
    title: "Now Or Never",
    artist: "Halsey",
    album: "hopeless fountain kingdom",
    display: true,
  },
  {
    title: "Sorry",
    artist: "Halsey",
    album: "hopeless fountain kingdom",
    display: true,
  },
  {
    title: "Walls Could Talk",
    artist: "Halsey",
    album: "hopeless fountain kingdom",
    display: true,
  },
  {
    title: "Hopeless (feat. Cashmere Cat)",
    artist: "Halsey",
    album: "hopeless fountain kingdom",
    display: true,
  },
  {
    title: "Graveyard",
    artist: "Halsey",
    album: "Manic",
    display: true,
  },
  {
    title: "You should be sad",
    artist: "Halsey",
    album: "Manic",
    display: true,
  },
  {
    title: "Forever ... (is a long time)",
    artist: "Halsey",
    album: "Manic",
    display: true,
  },
  {
    title: "I HATE EVERYBODY",
    artist: "Halsey",
    album: "Manic",
    display: true,
  },
  {
    title: "Without Me",
    artist: "Halsey",
    album: "Manic",
    display: true,
  },
  {
    title: "Finally // beautiful stranger",
    artist: "Halsey",
    album: "Manic",
    display: true,
  },
  {
    title: "killing boys",
    artist: "Halsey",
    album: "Manic",
    display: true,
  },
  {
    title: "wipe your tears",
    artist: "Halsey",
    album: "Manic",
    display: true,
  },
  {
    title: "I'm Not Mad",
    artist: "Halsey",
    album: "Manic",
    display: true,
  },
  {
    title: "Belles In Santa Fe",
    artist: "Halsey",
    album: "If I Can't Have Love, I Want Power",
    display: true,
  },
  {
    title: "Easier than Lying",
    artist: "Halsey",
    album: "If I Can't Have Love, I Want Power",
    display: true,
  },
  {
    title: "You asked for this",
    artist: "Halsey",
    album: "If I Can't Have Love, I Want Power",
    display: true,
  },
  {
    title: "1121",
    artist: "Halsey",
    album: "If I Can't Have Love, I Want Power",
    display: true,
  },
  {
    title: "honey",
    artist: "Halsey",
    album: "If I Can't Have Love, I Want Power",
    display: true,
  },
  {
    title: "Ya'aburnee",
    artist: "Halsey",
    album: "If I Can't Have Love, I Want Power",
    display: true,
  },
  {
    title: "So Good",
    artist: "Halsey",
    album: "Single",
    display: true,
  },
  {
    title: "Be Kind (with Halsey)",
    artist: "Marshmello",
    album: "Single",
    display: true,
  },
  {
    title: "In My Head",
    artist: "Fareoh",
    album: "Single",
    display: true,
  },
  {
    title: "Run Away",
    artist: "Fareoh",
    album: "Single",
    display: true,
  },
  {
    title: "iPad",
    artist: "The Chainsmokers",
    album: "So Far So Good",
    display: true,
  },
  {
    title: "traitor",
    artist: "Olivia Rodrigo",
    album: "SOUR",
    display: true,
  },
  {
    title: "drivers license",
    artist: "Olivia Rodrigo",
    album: "SOUR",
    display: true,
  },
  {
    title: "deja vu",
    artist: "Olivia Rodrigo",
    album: "SOUR",
    display: true,
  },
  {
    title: "good 4 u",
    artist: "Olivia Rodrigo",
    album: "SOUR",
    display: true,
  },
  {
    title: "favorite crime",
    artist: "Olivia Rodrigo",
    album: "SOUR",
    display: true,
  },
  {
    title: "vampire",
    artist: "Olivia Rodrigo",
    album: "GUTS",
    display: true,
  },
  {
    title: "ballad of a homeschooled girl",
    artist: "Olivia Rodrigo",
    album: "GUTS",
    display: true,
  },
  {
    title: "making the bed",
    artist: "Olivia Rodrigo",
    album: "GUTS",
    display: true,
  },
  {
    title: "logical",
    artist: "Olivia Rodrigo",
    album: "GUTS",
    display: true,
  },
  {
    title: "get him back!",
    artist: "Olivia Rodrigo",
    album: "GUTS",
    display: true,
  },
  {
    title: "love is embarrasing",
    artist: "Olivia Rodrigo",
    album: "GUTS",
    display: true,
  },
  {
    title: "the grudge",
    artist: "Olivia Rodrigo",
    album: "GUTS",
    display: true,
  },
  {
    title: "teenage dream",
    artist: "Olivia Rodrigo",
    album: "GUTS",
    display: true,
  },
  {
    title: "Used To Be Young",
    artist: "Miley Cyrus",
    album: "Endless Summer Vacation",
    display: true,
  },
  {
    title: "Minor Feelings",
    artist: "Rina Sawayama",
    album: "Hold The Girl",
    display: true,
  },
  {
    title: "Hold The Girl",
    artist: "Rina Sawayama",
    album: "Hold The Girl",
    display: true,
  },
  {
    title: "Catch Me In The Air",
    artist: "Rina Sawayama",
    album: "Hold The Girl",
    display: true,
  },
  {
    title: "Forgiveness",
    artist: "Rina Sawayama",
    album: "Hold The Girl",
    display: true,
  },
  {
    title: "Holy (Til You Let Me Go)",
    artist: "Rina Sawayama",
    album: "Hold The Girl",
    display: true,
  },
  {
    title: "Your Age",
    artist: "Rina Sawayama",
    album: "Hold The Girl",
    display: true,
  },
  {
    title: "Imagining",
    artist: "Rina Sawayama",
    album: "Hold The Girl",
    display: true,
  },
  {
    title: "Frankenstein",
    artist: "Rina Sawayama",
    album: "Hold The Girl",
    display: true,
  },
  {
    title: "Hurricanes",
    artist: "Rina Sawayama",
    album: "Hold The Girl",
    display: true,
  },
  {
    title: "Send My Love To John",
    artist: "Rina Sawayama",
    album: "Hold The Girl",
    display: true,
  },
  {
    title: "To Be Alive",
    artist: "Rina Sawayama",
    album: "Hold The Girl",
    display: true,
  },
  {
    title: "Cherry (Piano Version)",
    artist: "Rina Sawayama",
    album: "Single",
    display: true,
  },
  {
    title: "Kamikaze",
    artist: "Carly Rae Jepsen",
    album: "The Loveliest Time",
    display: true,
  },
  {
    title: "Kollage",
    artist: "Carly Rae Jepsen",
    album: "The Loveliest Time",
    display: true,
  },
  {
    title: "Psychedelic Switch",
    artist: "Carly Rae Jepsen",
    album: "The Loveliest Time",
    display: true,
  },
  {
    title: "Talking To Yourself",
    artist: "Carly Rae Jepsen",
    album: "The Loneliest Time",
    display: true,
  },
  {
    title: "Sideways",
    artist: "Carly Rae Jepsen",
    album: "The Loneliest Time",
    display: true,
  },
  {
    title: "Bends",
    artist: "Carly Rae Jepsen",
    album: "The Loneliest Time",
    display: true,
  },
  {
    title: "Bad Thing Twice",
    artist: "Carly Rae Jepsen",
    album: "The Loneliest Time",
    display: true,
  },
  {
    title: "Go Find Yourself Or Whatever",
    artist: "Carly Rae Jepsen",
    album: "The Loneliest Time",
    display: true,
  },
  {
    title: "The Loneliest Time (feat. Rufus Wainwright)",
    artist: "Carly Rae Jepsen",
    album: "The Loneliest Time",
    display: true,
  },
  {
    title: "Anxious",
    artist: "Carly Rae Jepsen",
    album: "The Loneliest Time",
    display: true,
  },
  {
    title: "No Thinking Over The Weekend",
    artist: "Carly Rae Jepsen",
    album: "The Loneliest Time",
    display: true,
  },
  {
    title: "Now That I Found You",
    artist: "Carly Rae Jepsen",
    album: "Dedicated",
    display: true,
  },
  {
    title: "Real Love",
    artist: "Carly Rae Jepsen",
    album: "Dedicated",
    display: true,
  },
  {
    title: "For Sure",
    artist: "Carly Rae Jepsen",
    album: "Dedicated",
    display: true,
  },
  {
    title: "This Love Isn't Crazy",
    artist: "Carly Rae Jepsen",
    album: "Dedicated Side B",
    display: true,
  },
  {
    title: "Run Away With Me",
    artist: "Carly Rae Jepsen",
    album: "E•MO•TION",
    display: true,
  },
  {
    title: "Never Get To Hold You",
    artist: "Carly Rae Jepsen",
    album: "E•MO•TION",
    display: true,
  },
];
